### ISSUE TITLE
Josh needs to add his email to the README.md file

### ISSUE THREAD

**Issue by dchenbecker** [JMS1138/dinoworld#3]
This is partly a "how do I branch and do things in git" and partly testing to make sure that Derek has the right permissions to merge and review things.

Make sure you're up-to-date on your main branch, then create a new branch in git. On that new branch, edit the README and update the `<email here>` to be your email. Make a new commit and push your new branch to GitHub. Once you've done that, the main GitHub project page (https://github.com/JMS1138/dinoworld) should offer to open a PR. Open a PR and send me the link so that I can review it and merge it.

**Comment by JMS1138** [comment]
added email address to readme
